version: '3'

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
    environment:
      SERVICES: sqs
    volumes:
      - "./.docker/volumes/localstack:/tmp/localstack"